// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Dota2BetaTestSchema;

namespace SteamEcon.Schema.Dota2BetaTestSchema
{
}

namespace Dota2BetaTestSchema
{
}
