// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Dota2Schema;

namespace SteamEcon.Schema.Dota2Schema
{
}

namespace Dota2Schema
{
}
