// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Portal2BetaSchema;

namespace SteamEcon.Schema.Portal2BetaSchema
{
}

namespace Portal2BetaSchema
{
}
