// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Portal2Schema;

namespace SteamEcon.Schema.Portal2Schema
{
    public class Portal2Schema
    {

        [JsonProperty("status")]
        public int Status { get; set; }

        [JsonProperty("items_game_url")]
        public string ItemsGameUrl { get; set; }

        [JsonProperty("qualities")]
        public Qualities Qualities { get; set; }

        [JsonProperty("qualityNames")]
        public QualityNames QualityNames { get; set; }

        [JsonProperty("originNames")]
        public IList<OriginName> OriginNames { get; set; }

        [JsonProperty("items")]
        public IList<Item> Items { get; set; }

        [JsonProperty("attributes")]
        public IList<Attribute> Attributes { get; set; }

        [JsonProperty("item_sets")]
        public IList<object> ItemSets { get; set; }

        [JsonProperty("attribute_controlled_attached_particles")]
        public IList<AttributeControlledAttachedParticle> AttributeControlledAttachedParticles { get; set; }
    }
}

namespace Portal2Schema
{
    public class Qualities
    {

        [JsonProperty("normal")]
        public int Normal { get; set; }

        [JsonProperty("rarity1")]
        public int Rarity1 { get; set; }

        [JsonProperty("rarity2")]
        public int Rarity2 { get; set; }

        [JsonProperty("vintage")]
        public int Vintage { get; set; }

        [JsonProperty("rarity3")]
        public int Rarity3 { get; set; }

        [JsonProperty("rarity4")]
        public int Rarity4 { get; set; }

        [JsonProperty("unique")]
        public int Unique { get; set; }

        [JsonProperty("community")]
        public int Community { get; set; }

        [JsonProperty("developer")]
        public int Developer { get; set; }

        [JsonProperty("selfmade")]
        public int Selfmade { get; set; }

        [JsonProperty("customized")]
        public int Customized { get; set; }

        [JsonProperty("strange")]
        public int Strange { get; set; }

        [JsonProperty("completed")]
        public int Completed { get; set; }
    }
    public class QualityNames
    {

        [JsonProperty("normal")]
        public string Normal { get; set; }

        [JsonProperty("rarity1")]
        public string Rarity1 { get; set; }

        [JsonProperty("rarity2")]
        public string Rarity2 { get; set; }

        [JsonProperty("vintage")]
        public string Vintage { get; set; }

        [JsonProperty("rarity3")]
        public string Rarity3 { get; set; }

        [JsonProperty("rarity4")]
        public string Rarity4 { get; set; }

        [JsonProperty("unique")]
        public string Unique { get; set; }

        [JsonProperty("community")]
        public string Community { get; set; }

        [JsonProperty("developer")]
        public string Developer { get; set; }

        [JsonProperty("selfmade")]
        public string Selfmade { get; set; }

        [JsonProperty("customized")]
        public string Customized { get; set; }

        [JsonProperty("strange")]
        public string Strange { get; set; }

        [JsonProperty("completed")]
        public string Completed { get; set; }
    }
    public class OriginName
    {

        [JsonProperty("origin")]
        public int Origin { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }
    public class Item
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("defindex")]
        public int Defindex { get; set; }

        [JsonProperty("item_class")]
        public string ItemClass { get; set; }

        [JsonProperty("item_type_name")]
        public string ItemTypeName { get; set; }

        [JsonProperty("item_name")]
        public string ItemName { get; set; }

        [JsonProperty("proper_name")]
        public bool ProperName { get; set; }

        [JsonProperty("item_slot")]
        public string ItemSlot { get; set; }

        [JsonProperty("item_quality")]
        public int ItemQuality { get; set; }

        [JsonProperty("image_inventory")]
        public string ImageInventory { get; set; }

        [JsonProperty("min_ilevel")]
        public int MinIlevel { get; set; }

        [JsonProperty("max_ilevel")]
        public int MaxIlevel { get; set; }

        [JsonProperty("image_url")]
        public string ImageUrl { get; set; }

        [JsonProperty("image_url_large")]
        public string ImageUrlLarge { get; set; }

        [JsonProperty("drop_type")]
        public string DropType { get; set; }

        [JsonProperty("capabilities")]
        public Capabilities Capabilities { get; set; }

        [JsonProperty("item_description")]
        public string ItemDescription { get; set; }
    }
    public class Capabilities
    {

        [JsonProperty("paintable")]
        public bool Paintable { get; set; }

        [JsonProperty("nameable")]
        public bool Nameable { get; set; }

        [JsonProperty("can_gift_wrap")]
        public bool CanGiftWrap { get; set; }

        [JsonProperty("can_craft_mark")]
        public bool CanCraftMark { get; set; }
    }
    public class Attribute
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("defindex")]
        public int Defindex { get; set; }

        [JsonProperty("attribute_class")]
        public string AttributeClass { get; set; }

        [JsonProperty("min_value")]
        public double MinValue { get; set; }

        [JsonProperty("max_value")]
        public double MaxValue { get; set; }

        [JsonProperty("description_string")]
        public string DescriptionString { get; set; }

        [JsonProperty("description_format")]
        public string DescriptionFormat { get; set; }

        [JsonProperty("effect_type")]
        public string EffectType { get; set; }

        [JsonProperty("hidden")]
        public bool Hidden { get; set; }

        [JsonProperty("stored_as_integer")]
        public bool StoredAsInteger { get; set; }
    }
    public class AttributeControlledAttachedParticle
    {

        [JsonProperty("system")]
        public string System { get; set; }

        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("attach_to_rootbone")]
        public bool AttachToRootbone { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("attachment")]
        public string Attachment { get; set; }
    }
}
