// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TF2Schema;

namespace SteamEcon.Schema.TF2Schema
{
}

namespace TF2Schema
{
}
